# Método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90). reshape(30,3)
data

array([[0.61700321, 0.08573929, 0.11997005],
       [0.32390719, 0.75597296, 0.58068524],
       [0.01260363, 0.50826077, 0.96468369],
       [0.24970864, 0.84015215, 0.29310449],
       [0.32581984, 0.82933612, 0.10934188],
       [0.79486156, 0.18573609, 0.17932147],
       [0.52645272, 0.54598841, 0.35962688],
       [0.4258965 , 0.69239199, 0.50019256],
       [0.80517765, 0.3841579 , 0.38303142],
       [0.51978109, 0.25791475, 0.35359092],
       [0.04006136, 0.91382448, 0.55191003],
       [0.36765813, 0.6310168 , 0.13411622],
       [0.63378069, 0.49124071, 0.82414522],
       [0.85668816, 0.04500742, 0.14519676],
       [0.2420119 , 0.24422993, 0.27066793],
       [0.61391109, 0.67817181, 0.7499907 ],
       [0.77662353, 0.967334  , 0.88290429],
       [0.30576595, 0.3536311 , 0.82164782],
       [0.86390628, 0.38947537, 0.737436  ],
       [0.7755764 , 0.87037071, 0.8946947 ],
       [0.55859618, 0.34871045, 0.03105071],
       [0.55207278, 0.45463675, 0.97824656],
       [0.

In [4]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers =np.vstack ([data[c1],data[c2]])
clust_centers

array([[0.04006136, 0.91382448, 0.55191003],
       [0.30576595, 0.3536311 , 0.82164782]])

In [5]:
from scipy.cluster.vq import vq

In [7]:
vq(data, clust_centers)

(array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 1]),
 array([0.81301066, 0.32605762, 0.36098995, 0.34111567, 0.53353796,
        0.82461286, 0.54696191, 0.44785689, 0.6653783 , 0.5234896 ,
        0.        , 0.60154093, 0.35571943, 0.92539175, 0.5653424 ,
        0.45322714, 0.77594489, 0.        , 0.56559444, 0.7021948 ,
        0.83005489, 0.30885654, 0.37962176, 0.83416386, 0.81558849,
        0.23329387, 0.68758029, 0.6934408 , 0.61782731, 0.42993616]))

In [8]:
from scipy.cluster.vq import kmeans

In [9]:
kmeans(data,clust_centers)

(array([[0.42040068, 0.47124149, 0.24806931],
        [0.60448907, 0.50717745, 0.83326221]]),
 0.3758224297011784)

In [10]:
kmeans (data, 2)

(array([[0.45182315, 0.40801049, 0.18883066],
        [0.53624893, 0.56322126, 0.77546229]]),
 0.37443343650044114)