# Regresion lineal en python
## El paquete scikit-learn para regresion lineal y la seleccion de rangos 

In [31]:
import numpy as np
import pandas as pd 
from sklearn.svm import SVR
from sklearn.feature_selection import RFE
import matplotlib.pyplot as plt
    

In [3]:
data = pd.read_csv ( "./Documents/Python Scripts/datasets/ads/Advertising.csv")

In [7]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [9]:
X = data[feature_cols]
Y = data["Sales"]

In [10]:
estimator = SVR(kernel="linear")
selector = RFE(estimator,2, step=1)
selector = selector.fit(X,Y)

In [11]:
selector.support_

array([ True,  True, False])

In [12]:
selector.ranking_

array([1, 1, 2])

In [18]:
from sklearn.linear_model import LinearRegression

In [24]:
x_pred = X[["TV", "Radio"]]

In [25]:
lm = LinearRegression()
lm.fit(x_pred,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
lm.intercept_

2.9210999124051362

In [28]:
lm.coef_

array([0.04575482, 0.18799423])

In [29]:
lm.score(x_pred,Y)

0.8971942610828956